(() => {
'use strict';
const VERSION='1.5.0';
const $=id=>document.getElementById(id);
function ready(){return typeof state!=='undefined'&&typeof matrixScore==='function'&&Array.isArray(state.players)}
function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,n))}
function injectStyles(){const s=document.createElement('style');s.textContent=`
.dm-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:11px}.dm-card{border:1px solid var(--line);background:#09130e;border-radius:15px;padding:12px}.dm-card strong{display:block;font-size:13px}.dm-card span{font-size:10px;color:var(--muted)}.dm-command{border:1px solid rgba(57,255,20,.32);background:linear-gradient(145deg,rgba(57,255,20,.09),#09130e);border-radius:18px;padding:14px;margin-top:12px}.dm-command h4{margin:0 0 4px;font-size:17px}.dm-command p{margin:0;color:var(--muted);font-size:11px;line-height:1.45}.dm-answer{margin-top:11px;border-top:1px solid var(--line);padding-top:11px}.dm-name{font-size:21px;font-weight:950}.dm-verdict{display:inline-block;margin-top:6px;padding:6px 9px;border-radius:999px;background:var(--accent);color:#05130a;font-size:10px;font-weight:950}.dm-confidence{font-size:30px;font-weight:950;color:var(--accent);float:right}.dm-reasons{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:11px}.dm-reason{border:1px solid var(--line);border-radius:11px;padding:8px;font-size:9px;color:var(--muted)}.dm-reason b{display:block;color:var(--text);font-size:11px;margin-bottom:2px}.dm-dna{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.dm-dna i{font-style:normal;border:1px solid #315742;color:var(--accent);border-radius:999px;padding:6px 8px;font-size:9px;font-weight:850}.dm-war{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.dm-war div{border:1px solid var(--line);border-radius:11px;padding:8px;text-align:center}.dm-war b{display:block;font-size:16px}.dm-war span{font-size:8px;color:var(--muted)}
@media(max-width:560px){.dm-grid{grid-template-columns:1fr}.dm-reasons{grid-template-columns:1fr}.dm-war{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function available(){return state.players.filter(p=>!state.drafted.has(p.id))}
function roster(){let ids=[];try{ids=JSON.parse(localStorage.getItem('ffm-fast-my-roster')||'[]')}catch(_){}const set=new Set(ids);return state.players.filter(p=>set.has(p.id))}
function best(){let top=null,score=-1;for(const p of available()){const s=matrixScore(p);if(s>score){score=s;top=p}}return top}
function positionCounts(players){return players.reduce((a,p)=>(a[p.position]=(a[p.position]||0)+1,a),{})}
function verdict(p){const pool=available().filter(x=>x.position===p.position).map(x=>({p:x,s:matrixScore(x)})).sort((a,b)=>b.s-a.s);const idx=pool.findIndex(x=>x.p.id===p.id);const gap=idx>=0&&pool[idx+1]?matrixScore(p)-pool[idx+1].s:10;const picks=Number(state.picksUntilNext||state.teams||12);if(gap>=7)return'DRAFT NOW';if(idx<=1&&picks<=6)return'DRAFT NOW';if(idx<=3&&picks>10)return'LIKELY AVAILABLE NEXT TURN';if(idx>8)return'WAIT';return'VALUE PICK'}
function dna(){const r=roster(),c=positionCounts(r),tags=[];if(!r.length)return['Build your roster to unlock DNA'];if((c.WR||0)>=2)tags.push('WR CORE');if((c.RB||0)>=2)tags.push('RB FOUNDATION');if(c.QB)tags.push('QB SECURED');if(c.TE)tags.push('TE SECURED');const avg=r.reduce((s,p)=>s+(p.metrics?.ceiling||50),0)/r.length;if(avg>=72)tags.push('HIGH CEILING');const avail=r.reduce((s,p)=>s+(p.metrics?.availability||75),0)/r.length;if(avail<72)tags.push('INJURY RISK');if(!(c.RB||0))tags.push('NEEDS RB');if(!(c.WR||0))tags.push('NEEDS WR');return tags.slice(0,5)}
function render(){if(!ready()||!state.players.length)return;const p=best();if(!p)return;const r=roster(),counts=positionCounts(r),conf=clamp(Math.round(matrixScore(p)*.72+(p.metrics?.availability||75)*.18+(p.metrics?.opportunity||60)*.1));const v=verdict(p);const host=$('decisionMatrixHost');if(!host)return;host.innerHTML=`<div class="dm-command"><div class="eyebrow">THE DECISION MATRIX</div><h4>What should I do right now?</h4><p>The Matrix combines your league settings, remaining player pool, roster construction, opportunity and risk.</p><div class="dm-answer"><span class="dm-confidence">${conf}%</span><div class="dm-name">${p.name}</div><div>${p.position} · ${p.team}</div><span class="dm-verdict">${v}</span><div class="dm-reasons"><div class="dm-reason"><b>${matrixScore(p)} Matrix</b>Overall decision score</div><div class="dm-reason"><b>${p.metrics?.opportunity||'—'} Opportunity</b>Expected role strength</div><div class="dm-reason"><b>${p.metrics?.ceiling||'—'} Ceiling</b>Upside profile</div></div></div></div><div class="dm-grid"><div class="dm-card"><strong>Roster DNA</strong><span>Your build updates with every MY TEAM pick.</span><div class="dm-dna">${dna().map(x=>`<i>${x}</i>`).join('')}</div></div><div class="dm-card"><strong>Draft War Room</strong><span>Live roster construction and pick context.</span><div class="dm-war"><div><b>${r.length}</b><span>MY PICKS</span></div><div><b>${state.picksUntilNext||state.teams}</b><span>TO NEXT PICK</span></div><div><b>${counts.RB||0}</b><span>RB</span></div><div><b>${counts.WR||0}</b><span>WR</span></div></div></div></div>`}
function init(){if(!ready())return setTimeout(init,100);injectStyles();const hero=document.querySelector('.hero');if(hero&&!$('decisionMatrixHost')){const h=document.createElement('div');h.id='decisionMatrixHost';hero.insertAdjacentElement('afterend',h)}const old=window.renderAll;if(typeof old==='function'){window.renderAll=function(){const x=old.apply(this,arguments);requestAnimationFrame(render);return x}}setInterval(render,1800);render();document.querySelectorAll('.brand small').forEach(el=>el.textContent=el.textContent.replace(/v\d+\.\d+\.\d+/,`v${VERSION}`));const f=document.querySelector('footer');if(f)f.innerHTML=f.innerHTML.replace(/v\d+\.\d+\.\d+/,`v${VERSION}`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();