(() => {
  'use strict';
  const ROSTER_KEY='ffm-fast-my-roster', BENCH_KEY='ffm-fast-bench', LINEUP_KEY='ffm-roster-lineup', PROFILE_KEY='ffm-league-profile-v2';
  const PROFILE=Object.freeze({QB:1,RB:2,WR:2,TE:1,FLEX:2,K:1,DST:1,BENCH:5});
  const FLEX=new Set(['RB','WR','TE']);
  function json(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch(_){return fallback}}
  function installProfile(){if(localStorage.getItem(PROFILE_KEY)==='game-of-throws-15')return;localStorage.setItem(LINEUP_KEY,JSON.stringify({QB:1,RB:2,WR:2,TE:1,FLEX:2,K:1,DST:1}));localStorage.setItem(PROFILE_KEY,'game-of-throws-15')}
  function snapshot(){const mine=new Set(json(ROSTER_KEY,[])),bench=new Set(json(BENCH_KEY,[])),players=(typeof state!=='undefined'&&Array.isArray(state.players))?state.players:[],counts={QB:0,RB:0,WR:0,TE:0,K:0,DST:0};for(const p of players)if(mine.has(p.id)&&!bench.has(p.id)&&counts[p.position]!==undefined)counts[p.position]++;const filled={};for(const p of ['QB','RB','WR','TE','K','DST'])filled[p]=Math.min(counts[p],PROFILE[p]);const flexFilled=Math.min(PROFILE.FLEX,['RB','WR','TE'].reduce((n,p)=>n+Math.max(0,counts[p]-PROFILE[p]),0));return{mine,bench,counts,filled,flexFilled,benchFilled:Math.min(5,bench.size)}}
  function openFor(p,s){return !!p&&((['QB','RB','WR','TE','K','DST'].includes(p.position)&&s.filled[p.position]<PROFILE[p.position])||(FLEX.has(p.position)&&s.flexFilled<2))}
  function starterOpen(s){return ['QB','RB','WR','TE','K','DST'].reduce((n,p)=>n+PROFILE[p]-s.filled[p],0)+(2-s.flexFilled)}
  function installScoreGuard(){if(window.__FFM_GAME_OF_THROWS_PROFILE__||typeof matrixScore!=='function')return;window.__FFM_GAME_OF_THROWS_PROFILE__=true;const base=matrixScore;matrixScore=function(p,round=Number(document.getElementById('round')?.value||1),includeScarcity=true){let score=base(p,round,includeScarcity);if(!includeScarcity||!p)return score;const s=snapshot(),r=Number(round||1),open=starterOpen(s);if(openFor(p,s)){if(FLEX.has(p.position)&&s.flexFilled<2)score+=4;if(['K','DST'].includes(p.position)){if(r>=9)score+=12;if(r>=12||open<=2)score+=18}}else if(open>0&&s.bench.size<5)score-=6;return Math.max(1,Math.round(score))}}
  function render(){const chips=document.getElementById('rosterNeedChips'),summary=document.getElementById('rosterNeedSummary');if(!chips||!summary)return;const s=snapshot(),parts=[['QB',s.filled.QB,1],['RB',s.filled.RB,2],['WR',s.filled.WR,2],['TE',s.filled.TE,1],['W/R/T',s.flexFilled,2],['K',s.filled.K,1],['DEF',s.filled.DST,1],['BENCH',s.benchFilled,5]];chips.innerHTML=parts.map(([p,n,t])=>`<span class="need-chip ${n<t?'open':'done'}">${p} ${n}/${t}</span>`).join('');const open=starterOpen(s)+(5-s.benchFilled);summary.textContent=open?`${open} of 15 roster slots open`:'All 15 roster slots filled'}
  function decorate(){render();const pick=typeof bestDraftPlayer==='function'?bestDraftPlayer():null,why=document.querySelector('#draftPick .why');if(!pick||!why)return;why.querySelectorAll('.game-profile-note').forEach(n=>n.remove());const s=snapshot();let text='';if(openFor(pick,s))text=`Fills an open Game of Throws starter/FLEX need. ${starterOpen(s)} starter slot${starterOpen(s)===1?'':'s'} remain.`;else if(s.benchFilled<5)text=`Starter needs are protected; build bench depth ${s.benchFilled}/5.`;if(text)why.insertAdjacentHTML('beforeend',`<span class="game-profile-note" style="display:block;margin-top:6px;color:var(--accent)"><strong>League fit:</strong> ${text}</span>`)}
  function init(){installProfile();installScoreGuard();const panel=document.getElementById('rosterNeeds');if(panel&&!panel.querySelector('.league-profile-badge'))panel.insertAdjacentHTML('beforeend','<div class="league-profile-badge" style="font-size:10px;color:var(--muted);margin-top:6px"><strong style="color:var(--accent)">Game of Throws:</strong> QB 1 · RB 2 · WR 2 · TE 1 · W/R/T 2 · K 1 · DEF 1 · Bench 5</div>');decorate();let queued=false;const draft=document.getElementById('draft');if(draft)new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}).observe(draft,{childList:true,subtree:true});document.addEventListener('click',()=>setTimeout(decorate,0),true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else setTimeout(init,0);
})();
