const test=require('node:test');
const assert=require('node:assert/strict');
const {normalizeLeagueSnapshot}=require('../season-core/contracts');
const {buildWeeklyAttackPlan}=require('../season-core/weekly-attack-plan');

const slots=[{id:'QB',type:'QB',count:1,eligiblePositions:['QB'],isBench:false,isReserve:false},{id:'RB',type:'RB',count:2,eligiblePositions:['RB'],isBench:false,isReserve:false},{id:'WR',type:'WR',count:2,eligiblePositions:['WR'],isBench:false,isReserve:false},{id:'TE',type:'TE',count:1,eligiblePositions:['TE'],isBench:false,isReserve:false},{id:'FLEX',type:'FLEX',count:1,eligiblePositions:['RB','WR','TE'],isBench:false,isReserve:false},{id:'BN',type:'BN',count:4,eligiblePositions:['QB','RB','WR','TE'],isBench:true,isReserve:false}];
const values={Q1:{position:'QB',value:80,projection:20},R1:{position:'RB',value:48,projection:9},R2:{position:'RB',value:45,projection:8},W1:{position:'WR',value:90,projection:18},W2:{position:'WR',value:86,projection:17},W3:{position:'WR',value:80,projection:14},T1:{position:'TE',value:70,projection:11},B1:{position:'WR',value:32,projection:4},Q2:{position:'QB',value:76,projection:18},R3:{position:'RB',value:82,projection:16},R4:{position:'RB',value:78,projection:15},W4:{position:'WR',value:50,projection:8},W5:{position:'WR',value:44,projection:7},T2:{position:'TE',value:65,projection:10},FA_RB:{position:'RB',value:78,projection:15},FA_WR:{position:'WR',value:60,projection:10}};
function build({week=7,mine=['Q1','R1','R2','W1','W2','W3','T1','B1'],other=['Q2','R3','R4','W4','W5','T2'],statuses={},freshness='fresh'}={}){return normalizeLeagueSnapshot({league:{leagueId:'L',platform:'sleeper',season:2026,teams:2,scoring:{rec:1},rosterSlots:slots},week,myRosterId:'1',opponentRosterId:'2',rosters:[{rosterId:'1',playerIds:mine},{rosterId:'2',playerIds:other}],playerPool:[...new Set([...mine,...other,'FA_RB','FA_WR'])].map(id=>({id})),playerStatuses:statuses,freshness:{status:freshness,asOf:'2026-09-08T10:00:00.000Z',source:'sleeper'}})}

test('full season replay adapts when waiver ownership changes between refreshes',()=>{const first=build();const firstPlan=buildWeeklyAttackPlan(first,'1',values);assert.equal(firstPlan.waiverMove.addPlayerId,'FA_RB');const second=build({other:['Q2','R3','R4','W4','W5','T2','FA_RB']});assert.equal(second.freeAgentPlayerIds.includes('FA_RB'),false);const secondPlan=buildWeeklyAttackPlan(second,'1',values);assert.notEqual(secondPlan.waiverMove?.addPlayerId,'FA_RB');});
test('full season replay reacts to injury changes without treating old health as authoritative',()=>{const healthy=build();const before=buildWeeklyAttackPlan(healthy,'1',values);assert.equal(before.urgentStatusAlerts.some(a=>a.playerId==='R1'),false);const injured=build({statuses:{R1:{status:'Out'}}});const after=buildWeeklyAttackPlan(injured,'1',values);assert.ok(after.urgentStatusAlerts.some(a=>a.playerId==='R1'&&a.status==='OUT'));assert.equal(after.lineup.starters.some(s=>s.playerId==='R1'),false);});
test('full season replay preserves recommendations but lowers confidence when snapshot becomes stale',()=>{const fresh=buildWeeklyAttackPlan(build(),'1',values);const stale=buildWeeklyAttackPlan(build({freshness:'stale'}),'1',values);assert.ok(stale.confidence<fresh.confidence);assert.equal(stale.freshness.status,'stale');assert.ok(stale.actions.length>0);});
test('alternate league shape still produces a legal attack plan without Game of Throws assumptions',()=>{const altSlots=[{id:'QB',type:'QB',count:1,eligiblePositions:['QB'],isBench:false,isReserve:false},{id:'RB',type:'RB',count:1,eligiblePositions:['RB'],isBench:false,isReserve:false},{id:'WR',type:'WR',count:1,eligiblePositions:['WR'],isBench:false,isReserve:false},{id:'SF',type:'SUPER_FLEX',count:1,eligiblePositions:['QB','RB','WR','TE'],isBench:false,isReserve:false},{id:'BN',type:'BN',count:3,eligiblePositions:['QB','RB','WR','TE'],isBench:true,isReserve:false}];const s=normalizeLeagueSnapshot({league:{leagueId:'ALT',platform:'sleeper',season:2026,teams:2,scoring:{},rosterSlots:altSlots},week:8,myRosterId:'1',opponentRosterId:'2',rosters:[{rosterId:'1',playerIds:['Q1','R1','W1','W2']},{rosterId:'2',playerIds:['Q2','R3','W4','T2']}],playerPool:['Q1','R1','W1','W2','Q2','R3','W4','T2','FA_RB'].map(id=>({id})),freshness:{status:'fresh'}});const p=buildWeeklyAttackPlan(s,'1',values);assert.equal(p.lineup.requiredStarterSlots,4);assert.equal(p.lineup.legal,true);});
