const test=require('node:test');
const assert=require('node:assert/strict');
const {normalizeLeagueSnapshot}=require('../season-core/contracts');
const {buildWeeklyAttackPlan}=require('../season-core/weekly-attack-plan');
const slots=[{id:'QB',type:'QB',count:1,eligiblePositions:['QB'],isBench:false,isReserve:false},{id:'RB',type:'RB',count:2,eligiblePositions:['RB'],isBench:false,isReserve:false},{id:'WR',type:'WR',count:2,eligiblePositions:['WR'],isBench:false,isReserve:false},{id:'TE',type:'TE',count:1,eligiblePositions:['TE'],isBench:false,isReserve:false},{id:'FLEX',type:'FLEX',count:1,eligiblePositions:['RB','WR','TE'],isBench:false,isReserve:false},{id:'BN',type:'BN',count:4,eligiblePositions:['QB','RB','WR','TE'],isBench:true,isReserve:false}];
function make(){const rosters=[{rosterId:'1',playerIds:['Q1','R1','R2','W1','W2','W3','T1','B1']},{rosterId:'2',playerIds:['Q2','R3','R4','W4','W5','T2']}];return normalizeLeagueSnapshot({league:{leagueId:'L',platform:'sleeper',season:2026,teams:2,scoring:{rec:1},rosterSlots:slots},week:7,myRosterId:'1',opponentRosterId:'2',rosters,playerPool:[...rosters.flatMap(r=>r.playerIds),'FA_RB','FA_WR'].map(id=>({id})),playerStatuses:{R2:{status:'Questionable'},W5:{status:'Out'}},freshness:{status:'fresh',asOf:'2026-09-08T10:00:00.000Z'}})}
const values={Q1:{position:'QB',value:80,projection:20},R1:{position:'RB',value:48,projection:9},R2:{position:'RB',value:45,projection:8},W1:{position:'WR',value:90,projection:18},W2:{position:'WR',value:86,projection:17},W3:{position:'WR',value:80,projection:14},T1:{position:'TE',value:70,projection:11},B1:{position:'WR',value:32,projection:4},Q2:{position:'QB',value:76,projection:18},R3:{position:'RB',value:82,projection:16},R4:{position:'RB',value:78,projection:15},W4:{position:'WR',value:50,projection:8},W5:{position:'WR',value:44,projection:7},T2:{position:'TE',value:65,projection:10},FA_RB:{position:'RB',value:78,projection:15},FA_WR:{position:'WR',value:60,projection:10}};
test('composes the complete weekly attack plan from all season intelligence engines',()=>{const p=buildWeeklyAttackPlan(make(),'1',values);assert.equal(p.week,7);assert.equal(typeof p.rosterGrade,'number');assert.ok(p.biggestWeakness);assert.ok(p.lineup);assert.ok(p.waiverMove);assert.ok(p.opponent);assert.ok(Array.isArray(p.urgentStatusAlerts));});
test('prioritizes explicit actions rather than generic summaries',()=>{const p=buildWeeklyAttackPlan(make(),'1',values);assert.ok(p.actions.length>=3);assert.ok(p.actions.some(a=>a.type==='WAIVER'));assert.ok(p.actions.some(a=>a.type==='LINEUP'));assert.ok(p.actions.some(a=>a.type==='OPPONENT'))});
test('surfaces add drop and status details in the attack plan',()=>{const p=buildWeeklyAttackPlan(make(),'1',values);assert.equal(p.waiverMove.addPlayerId,'FA_RB');assert.ok(p.waiverMove.dropPlayerId);assert.ok(p.urgentStatusAlerts.some(a=>a.playerId==='R2'&&a.status==='QUESTIONABLE'));});
test('propagates stale-data risk instead of presenting stale advice as certain',()=>{const s=make();const stale={...s,freshness:{...s.freshness,status:'stale'}};const p=buildWeeklyAttackPlan(stale,'1',values);assert.equal(p.freshness.status,'stale');assert.ok(p.confidence<100);assert.ok(p.actions.every(a=>typeof a.confidence==='number'&&typeof a.risk==='number'));});
