const VERSION='1.5.1';
const NOW=new Date();
const SEASON=NOW.getUTCMonth()>=2?NOW.getUTCFullYear():NOW.getUTCFullYear()-1;
const FANTASY_POSITIONS=new Set(['QB','RB','WR','TE']);
const TEAMS={1:'ATL',2:'BUF',3:'CHI',4:'CIN',5:'CLE',6:'DAL',7:'DEN',8:'DET',9:'GB',10:'TEN',11:'IND',12:'KC',13:'LV',14:'LAR',15:'MIA',16:'MIN',17:'NE',18:'NO',19:'NYG',20:'NYJ',21:'PHI',22:'ARI',23:'PIT',24:'LAC',25:'SF',26:'SEA',27:'TB',28:'WSH',29:'CAR',30:'JAX',33:'BAL',34:'HOU'};
const TEAM_IDS=Object.keys(TEAMS);
const cache=new Map();
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));

function availability(status){const s=String(status?.name||status||'ACTIVE').toUpperCase();if(s.includes('ACTIVE')||s.includes('NORMAL'))return 96;if(s.includes('QUESTION'))return 82;if(s.includes('DOUBT'))return 58;if(s.includes('OUT')||s.includes('RESERVE')||s.includes('IR')||s.includes('PUP')||s.includes('SUSP'))return 28;return 76}
function roleBase(pos,depth){const table={QB:[76,50,40,34],RB:[75,67,58,50,44,40],WR:[76,72,66,58,51,45,41],TE:[69,57,49,43,39]};const a=table[pos]||[50];return a[Math.min(depth,a.length-1)]}
function metrics(pos,depth,years,status){const role=roleBase(pos,depth),veteran=Math.min(5,Math.max(0,years))*.8,rookie=years===0,avail=availability(status),production=clamp(role+veteran-(depth>1?3:0)),opportunity=clamp(role+(depth===0?7:depth===1?3:-2)),consistency=clamp(role*.64+avail*.30+veteran),ceiling=clamp(role+(rookie?9:5)+(depth===0?4:0)),trend=rookie?59:52,tov=clamp(opportunity*.7+ceiling*.3),mvi=clamp(100-(consistency*.62+avail*.38));return{production:Math.round(production),opportunity:Math.round(opportunity),consistency:Math.round(consistency),ceiling:Math.round(ceiling),trend:Math.round(trend),tov:Math.round(tov),mvi:Math.round(mvi),availability:Math.round(avail)}}

async function fetchJson(url,timeout=6500){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{signal:controller.signal,cache:'no-store',headers:{Accept:'application/json','User-Agent':`Fantasy-Football-Matrix/${VERSION}`}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function fetchRoster(id){const url=`https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${id}/roster`;let last;for(let attempt=0;attempt<2;attempt++){try{return{id,data:await fetchJson(url,attempt?8500:6000)}}catch(e){last=e;if(!attempt)await new Promise(r=>setTimeout(r,120))}}throw last}
function normalizeRoster(id,data){const team=TEAMS[id]||id,out=[],depth={};for(const group of data?.athletes||[]){for(const a of group?.items||[]){const pos=a?.position?.abbreviation;if(!FANTASY_POSITIONS.has(pos)||!a?.id||!(a.fullName||a.displayName))continue;const d=depth[pos]||0;depth[pos]=d+1;const years=num(a.experience?.years),status=a.status?.name||a.status?.type||'Active';out.push({id:String(a.id),name:a.fullName||a.displayName,position:pos,team,status,yearsExp:years,rookie:years===0,games:0,avgPoints:0,floor:0,ceiling:0,headshot:a.headshot?.href||'',metrics:metrics(pos,d,years,status)})}}return out}

async function loadRosters(){const hit=cache.get('rosters');if(hit&&hit.expires>Date.now())return hit.value;const players=[],failed=[];for(let i=0;i<TEAM_IDS.length;i+=4){const chunk=TEAM_IDS.slice(i,i+4);const results=await Promise.allSettled(chunk.map(fetchRoster));for(const result of results){if(result.status==='fulfilled')players.push(...normalizeRoster(result.value.id,result.value.data));else failed.push(String(result.reason?.message||result.reason))}}const unique=[...new Map(players.map(p=>[p.id,p])).values()];const teamsLoaded=TEAM_IDS.length-failed.length;if(unique.length<40)throw new Error(`ESPN roster feed returned only ${unique.length} fantasy players from ${teamsLoaded} teams`);const value={players:unique,teamsLoaded,failures:failed.length,source:'ESPN Public NFL API',fallback:teamsLoaded<32};cache.set('rosters',{value,expires:Date.now()+5*60*1000});return value}

async function live(scoring){try{const board=await fetchJson('https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100',5000);const events=Array.isArray(board?.events)?board.events:[],active=events.filter(e=>e?.status?.type?.state==='in');return{games:active.length,events:active.map(e=>({id:e.id,name:e.name,status:e?.status?.type?.shortDetail||'LIVE'})),season:board?.season?.year||SEASON,week:board?.week?.number||null,error:''}}catch(e){return{games:0,events:[],season:SEASON,week:null,error:String(e?.message||e)}}}
function sortPlayers(players){const score=p=>p.metrics.production*.34+p.metrics.opportunity*.26+p.metrics.ceiling*.16+p.metrics.consistency*.10+p.metrics.availability*.08+p.metrics.trend*.06;return players.sort((a,b)=>score(b)-score(a)).slice(0,500)}

module.exports=async function handler(req,res){try{const raw=String(req.query?.scoring||'ppr').toLowerCase();const scoring=raw==='standard'?'standard':raw==='half'?'half':'ppr';const base=await loadRosters();const liveData=await live(scoring);const players=sortPlayers(base.players);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');res.status(200).json({version:VERSION,generatedAt:new Date().toISOString(),currentSeason:liveData.season,statsSeason:SEASON,scoring,liveGames:liveData.games,liveEvents:liveData.events,health:{online:true,primary:base.source,teamsLoaded:base.teamsLoaded,rosterFailures:base.failures,liveFeed:liveData.error?'degraded':'online'},source:{name:base.source,live:'ESPN public scoreboard',note:base.teamsLoaded===32?`ESPN NFL player engine online · 32/32 team rosters loaded`:`ESPN NFL player engine online · ${base.teamsLoaded}/32 team rosters loaded · partial roster mode`,fallback:base.fallback,liveError:liveData.error},players})}catch(error){console.error('nfl-data fatal',error);res.setHeader('Cache-Control','no-store');res.status(503).json({error:'Football data engine unavailable.',detail:String(error?.message||error),version:VERSION})}}
module.exports.config={maxDuration:60};
